name: banjohouse
description: Automation app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.9.0-15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^1.1.0
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true
